### PR TITLE
Update Path_A_e1-e2-allowlist.json

### PR DESCRIPTION
**Pull request by maximusunc**

### CODE REVIEW

**Review by bill-baumgartner — COMMENTED** [review]
Documenting our zoom chat conversation here for posterity: 

Ideally we would use `infores:text-mining-provider-targeted` here, though I understand there is an issue with the allowlist specifically targeting KPs served by Service Provider. This is a similar issue that was found with trying to access Multiomics from the workflow runner (see https://github.com/TranslatorSRI/CQS/issues/1)

The text mining cooccurrence end point does not make use of the predicates for this edge, so this change shouldn't result in any new results. 

Also, the connections between n1 & n2 that could be provided by the literature cooccurrence data are potentially much more generic than or even contradictory to `biolink:affects_activity_of` or `biolink:interacts_with`.

**Comment by karafecho** [comment]
@bill-baumgartner : Thanks for your comments. It looks like we did use `infores:text-mining-provider-targeted` on one of the queries (https://github.com/NCATSTranslator/Clinical-Data-Committee-Tracking-Voting/blob/main/GetCreative()_DrugDiscoveryRepurposing_RarePulmonaryDisease/Path_A/Path_A_e1-e2-e3-allowlist.json), just not the one here. I think that was a simple oversight.

It sounds like you're okay with `biolink:affects_activity_of` and `biolink:interacts_with`, as long as we're targeting `infores:text-mining-provider-targeted`.

The Service Provider issue is a blocker, unfortunately. FWIW, the approach that Multiomics has decided to adopt in order to overcome this issue is to migrate to Automat (https://automat.renci.org/). Happy to discuss this option with you.

Note that Max and I noticed that the SmartAPI registry for `infores:text-mining-provider-targeted` doesn't include a meta-KG endpoint. This will prevent ARAGORN, e.g., from recognizing `infores:text-mining-provider-targeted` as part of its query graph planning. Not really relevant for now, due to the Service Provider issue, but probably something to consider in the future.

**Review by karafecho — CHANGES_REQUESTED** [review]
Please change `infores:text-mining-kp` and `infores:text-mining-provider-cooccurrence` to `infores:text-mining-provider-targeted`.

**Review by karafecho — APPROVED** [review]

**Comment by karafecho** [comment]
@maximusunc @bill-baumgartner: Can we include `infores:automat-text-mining-provider` in the `allowlist`?

```
- id: infores:automat-text-mining-provider
    status: deprecated
    name: Automat Textmining KP
    knowledge level: curated
    agent type: not_provided
    description: A literature co-occurrence graph created by the Translator Text Mining KP.
```

**Pull request merged**
